global:
  num_rounds: 50
  model: 'CNN'
  dataset: 'FashionMNIST'  # 'MNIST', 'FashionMNIST', 'CIFAR10'
  seed: 42          # Not using for now
  num_clients: 40
  partition: 'iid'  #  'iid', 'label_skew' (non-iid), 'dirichlet' (non-iid)
  network_simulation: True
  model_compression: True

clustering:
  strategy: 'device-centric' # 'random', 'device-centric', 'network-centric'
  num_clusters: 4
  cluster_criteria: ['compute_power'] # 'compute_power', 'location'

aggregation:
  intra_cluster: 'sync' # 'async', 'sync'
  inter_cluster: 'sync'
  stepwise_agg: True

compression:
  compress_per_cluster: True
  method: 'layer-wise-pruning'